// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apowrdellfsklcmhzplx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwb3dyZGVsbGZza2xjbWh6cGx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1MzI3MjUsImV4cCI6MjA3OTEwODcyNX0.lGKDb__lUnMaQV0xmhXe5CL8jioXn7D9t_LVRErxxk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});